import { defineConfig } from 'astro/config';
import { SITE } from './src/lib/site.js';

// NOTE: sitemap.xml is generated by src/pages/sitemap.xml.js, not by
// @astrojs/sitemap. That package broke a RigFloorHQ build on a minor bump
// (3.7.1 crashed in astro:build:done), and the fix there was to pin it.
// A hand-written endpoint has nothing to pin — and because it reads
// src/data and src/lib directly, new cities, businesses, guides and
// glossary terms appear in the sitemap with no extra config.
//
// ⚠️ To change the production domain, edit `domain` in src/lib/site.js.
// That is the single source of truth used here, in the sitemap, in llms.txt
// and in every page's canonical and OG tags.
export default defineConfig({
  site: SITE.domain,
  trailingSlash: 'always',
  build: {
    format: 'directory', // clean URLs: /garage-door-repair/texas/houston/

    // The bundled stylesheet was the last render-blocking request on the
    // critical path: 5.1 KiB costing 160ms on throttled mobile, and the only
    // entry left in Lighthouse's render-blocking list once the Google Fonts
    // origins were removed. At that size inlining is strictly better than a
    // second round trip — it arrives with the HTML, so first paint waits on
    // nothing but the document.
    //
    // 'always' rather than 'auto': auto only inlines below a size threshold,
    // and a stylesheet that grows past it would silently revert to a blocking
    // <link> — a performance regression with no code change to point at.
    //
    // The trade is that ~5 KiB is repeated in all 976 pages instead of being
    // cached once. That is the right way round here: this is a directory whose
    // visitors arrive cold from search on one page, so a shared cache entry
    // they never get a second hit from buys nothing.
    inlineStylesheets: 'always',
  },
});
