import { defineConfig } from 'astro/config';
import { SITE } from './src/lib/site.js';

// NOTE: sitemap.xml is generated by src/pages/sitemap.xml.js, not by
// @astrojs/sitemap. That package broke a RigFloorHQ build on a minor bump
// (3.7.1 crashed in astro:build:done), and the fix there was to pin it.
// A hand-written endpoint has nothing to pin — and because it reads
// src/data and src/lib directly, new cities, businesses, guides and
// glossary terms appear in the sitemap with no extra config.
//
// ⚠️ To change the production domain, edit `domain` in src/lib/site.js.
// That is the single source of truth used here, in the sitemap, in llms.txt
// and in every page's canonical and OG tags.
export default defineConfig({
  site: SITE.domain,
  trailingSlash: 'always',
  build: {
    format: 'directory', // clean URLs: /garage-door-repair/texas/houston/
  },
});
